/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Create a new user. If no password is provided, the account is
         *     passwordless and login is governed by config.ALLOW_PASSWORDLESS_LOGIN
         *     at the token endpoint.
         */
        post: operations["register_user_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Review */
        post: operations["submit_review_cards__card_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create New Card */
        post: operations["create_new_card_cards__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forests/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Forest
         * @description Executes a typed pipeline against the given context ids.
         *
         *     Item 32a: the route no longer constructs the executor inline or
         *     takes a session dependency. The executor is injected fully wired —
         *     both the LineageRepositoryPort and the TagFilterRepositoryPort are
         *     already composed into it by get_pipeline_executor. FastAPI's
         *     dependency caching ensures the session backing both Ports is the
         *     same per-request session.
         *
         *     Pydantic has already validated the entire typed DSL (parse-time).
         *     The try/except remains defensive against runtime-only DSL errors —
         *     tag-DSL parse failures inside FilterSelection.tag_expression are
         *     the only remaining runtime PipelineDSLError path (the nested-
         *     filter case from pre-32a is now a parse-time error thanks to the
         *     BaseSelection vs Selection split in domain/pipeline_dsl.py).
         */
        post: operations["query_forest_forests_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__key__get"];
        /**
         * Update Document
         * @description Stateless Upsert for document data.
         *     Works natively on both Postgres and SQLite.
         */
        put: operations["update_document_documents__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Resources
         * @description List the names of all registered static resources.
         *
         *     Returns a sorted list of slugs that can be fetched via GET
         *     /resources/{name}. Useful for frontend discovery — lets the UI
         *     know what's available without hardcoding the catalog.
         */
        get: operations["list_resources_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resource
         * @description Fetch the content of a named static resource.
         *
         *     Returns a generic envelope: `{"name": <slug>, "content": <any>}`.
         *     The `content` field's shape is resource-specific; consumers are
         *     expected to know what to expect for the resource they asked for.
         *
         *     Raises:
         *         404 (via ResourceNotFoundError): `name` is not registered.
         *             The response body includes a message listing known
         *             resources.
         */
        get: operations["get_resource_resources__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tags
         * @description Returns a list of all tags and their usage counts across all cards.
         *
         *     Item 32a.2: service is now Port-pure and fully wired by DI — the
         *     route doesn't construct StatsEngine inline or take a session
         *     dependency. The service's repository shares the request-scoped
         *     session via FastAPI's dependency caching.
         *
         *     When tenancy lands (item 15), user_id becomes a parameter to
         *     service.compute_tag_usage(user_id=user_id) and the adapter adds
         *     the corresponding WHERE clause. Route change is one line; service
         *     change is additive; adapter change is additive.
         */
        get: operations["get_tags_stats_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/forests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Forests
         * @description Returns a summary of all root game sources, including the total
         *     number of descendant cards, aggregated reviews, and average
         *     Ebisu recall per forest.
         *
         *     Item 32a.2: aggregation lives in StatsService.compute_forest_
         *     summaries (pure Python over ForestMemberRow DTOs); the recursive
         *     root-mapping CTE and the card/game_source joins live in
         *     StatsRepository. The route is a three-liner.
         */
        get: operations["get_forests_stats_forests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AncestorSelection
         * @description The n-th ancestor of the context card (n=1 means parent).
         */
        AncestorSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "AncestorSelection";
            /**
             * N
             * @default 1
             */
            n: number;
        };
        /**
         * BfsOrder
         * @description Equivalent to DepthKey.
         */
        BfsOrder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bfs_order";
        };
        /** Body_login_for_access_token_auth_token_post */
        Body_login_for_access_token_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * CardCreate
         * @description Request body shape for POST /cards/.
         *
         *     Post-34b Commit 3: only `raw_content` is accepted for the content
         *     field. The transitional alias for `sgf` is gone. If the frontend
         *     sends a legacy shape the request fails at parse time with a
         *     clear Pydantic error — which is the correct diagnostic, not a
         *     silent misbinding.
         *
         *     Domain-specific grading configuration (KataGo visits, palette,
         *     gamma) travels inside `grading_parameter.data`. This DTO doesn't
         *     validate the blob's contents — it's the frontend's contract with
         *     the specific backend grading logic.
         */
        CardCreate: {
            /** Num Moves */
            num_moves: number;
            /** Grading Parameter */
            grading_parameter?: {
                [key: string]: unknown;
            } | null;
            /**
             * Raw Content
             * @description The raw domain content (SGF for Go, PGN for Chess, etc.). Normalized canonically by the configured PositionNormalizer before storage.
             */
            raw_content: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Parent Card Id */
            parent_card_id?: number | null;
            game_metadata?: components["schemas"]["GameSourceCreate"] | null;
        };
        /**
         * CardCreateResponse
         * @description Strongly-typed response for POST /cards/. Replaces the prior
         *     Dict[str, Any], which provided no information to OpenAPI consumers
         *     (and therefore no information to any code-generated TypeScript
         *     client downstream — see item 30). Item 4.
         */
        CardCreateResponse: {
            /**
             * Status
             * @constant
             */
            status: "created";
            /** Card Id */
            card_id: number;
        };
        /**
         * CardWithRecall
         * @description A Card augmented with its current Bayesian recall projection.
         *
         *     The wire shape. Post-34b Commit 3, it still emits the legacy
         *     `normalized_sgf` and `default_visits` field names via
         *     @computed_field shims for stale-client backward compatibility.
         *     These shims protect users whose cached browser bundle hasn't
         *     picked up the Commit 2 frontend yet.
         *
         *     The shims are purely additive — they synthesize from fields that
         *     already exist — and have zero cost for modern clients that read
         *     the canonical names. A later commit-3b drops them once the stale-
         *     client window is exhausted.
         */
        CardWithRecall: {
            /** Id */
            id: number;
            /** Num Moves */
            num_moves: number;
            /** Alpha */
            alpha: number;
            /** Beta */
            beta: number;
            /** T */
            t: number;
            /** Last Reviewed At */
            last_reviewed_at: string | null;
            /**
             * Creation Date
             * Format: date-time
             */
            creation_date: string;
            /** Num Reviews */
            num_reviews: number;
            /** Suspended */
            suspended: boolean;
            /** Grading Parameter */
            grading_parameter: {
                [key: string]: unknown;
            } | null;
            /** Canonical Content */
            canonical_content: string;
            /** Card Source Id */
            card_source_id?: number | null;
            /** Current Recall */
            current_recall: number;
            /** Halflife Units */
            halflife_units: number;
            /**
             * Normalized Sgf
             * @description Stale-client compat shim. Returns canonical_content under the
             *     pre-34b-Commit-3 field name.
             *
             *     Safe to remove in commit-3b (scheduled: once stale-client
             *     window is closed — typically 7–30 days after Commit 2 is
             *     live in production, operator's judgment).
             */
            readonly normalized_sgf: string;
            /**
             * Default Visits
             * @description Stale-client compat shim. Synthesizes the pre-34b-Commit-3
             *     top-level `default_visits` field by reaching into
             *     grading_parameter.data.default_visits (where the value
             *     actually lives post-Commit-3).
             *
             *     Returns 1000 as a sentinel if the grading_parameter doesn't
             *     contain the nested value — this matches the historical
             *     schema default and shouldn't happen for any row that went
             *     through CardService.create_card since Commit 1 (which always
             *     merges the value into the JSON).
             *
             *     Safe to remove in commit-3b.
             */
            readonly default_visits: number;
        };
        /**
         * CentroidOrder
         * @description Equivalent to CentroidRankKey.
         */
        CentroidOrder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "centroid_order";
        };
        /** CentroidRankKey */
        CentroidRankKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CentroidRankKey";
        };
        /**
         * ContextSelection
         * @description Just the context card itself.
         */
        ContextSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ContextSelection";
        };
        /** DepthKey */
        DepthKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DepthKey";
        };
        /**
         * DescendantSelection
         * @description All cards descended from the context, optionally bounded by depth.
         */
        DescendantSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DescendantSelection";
            /** Max Depth */
            max_depth?: number | null;
        };
        /**
         * DfsPostorder
         * @description Equivalent to LexicographicOrder(keys=[HeightKey, HeavyPathRankKey]).
         */
        DfsPostorder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dfs_postorder";
        };
        /**
         * DfsPreorder
         * @description Equivalent to HeavyPathRankKey.
         */
        DfsPreorder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dfs_preorder";
        };
        /** DocumentUpdate */
        DocumentUpdate: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** EbisuRecallKey */
        EbisuRecallKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "EbisuRecallKey";
        };
        /**
         * FilterSelection
         * @description Wraps a BaseSelection with a tag-DSL expression. By design,
         *     `base` is typed as BaseSelection — filter cannot be nested inside
         *     another filter. This is a parse-time invariant; the previous
         *     runtime check in build_selection_cte (item 31) is no longer
         *     reachable for well-typed input.
         */
        FilterSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "filter";
            /** Tag Expression */
            tag_expression: string;
            /** Base */
            base: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
        };
        /**
         * ForestQuery
         * @description The wire-level request body for POST /forests/query.
         *
         *     Structural invariants enforced by a model_validator:
         *       1. First stage must be 'select'.
         *       2. No subsequent stage may be 'select'.
         *
         *     Field-level validation (each variant's fields, each numeric bound,
         *     each discriminator value) is handled by Pydantic's discriminated-
         *     union machinery. The recently-added nested-filter rule (32a) is
         *     enforced by BaseSelection's absence of FilterSelection — no runtime
         *     check needed.
         */
        ForestQuery: {
            /** Context Ids */
            context_ids: number[];
            /** Pipeline */
            pipeline: (components["schemas"]["SelectStage"] | components["schemas"]["TakeStage"] | components["schemas"]["ShuffleStage"] | components["schemas"]["OrderStage"])[];
        };
        /** ForestStat */
        ForestStat: {
            /** Root Card Id */
            root_card_id: number;
            /** Game Source Id */
            game_source_id: number;
            /** Description */
            description: string | null;
            /** Player White */
            player_white: string | null;
            /** Player Black */
            player_black: string | null;
            /** Total Cards */
            total_cards: number;
            /** Total Reviews */
            total_reviews: number;
            /** Average Recall */
            average_recall: number;
        };
        /**
         * FringeFirst
         * @description Equivalent to LexicographicOrder(keys=[HeightKey, DepthKey]).
         */
        FringeFirst: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fringe_first";
        };
        /**
         * GameSourceCreate
         * @description Metadata for minting a brand new root card.
         */
        GameSourceCreate: {
            /** Player White */
            player_white?: string | null;
            /** Player Black */
            player_black?: string | null;
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeavyPathRankKey */
        HeavyPathRankKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HeavyPathRankKey";
        };
        /** HeightKey */
        HeightKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HeightKey";
        };
        /** IntersectSelection */
        IntersectSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "intersect";
            /** A */
            a: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
            /** B */
            b: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
        };
        /** LexicographicOrder */
        LexicographicOrder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LexicographicOrder";
            /** Keys */
            keys: (components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"])[];
        };
        /**
         * MainLineFirst
         * @description Equivalent to LexicographicOrder(keys=[HeavyPathRankKey, NumReviewsKey]).
         */
        MainLineFirst: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "main_line_first";
        };
        /** Negated */
        Negated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "negated";
            /** Key */
            key: components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"];
        };
        /** NumMovesKey */
        NumMovesKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NumMovesKey";
        };
        /** NumReviewsKey */
        NumReviewsKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NumReviewsKey";
        };
        /**
         * OrderStage
         * @description Re-sort the pool by the given key.
         */
        OrderStage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "order";
            /** Ordering */
            ordering: components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"];
        };
        /**
         * ResourceResponse
         * @description The wire shape for GET /resources/{name}.
         *
         *     Generic envelope: `content` is typed as `Any` because the payload
         *     shape varies per resource. This is a deliberate concession —
         *     Pydantic doesn't validate the inner structure, and downstream
         *     consumers (the frontend) are responsible for knowing the shape
         *     for the resource they asked for.
         *
         *     The alternative (discriminated union typed per resource) would be
         *     architecturally purer but over-engineered for a handful of static
         *     JSON blobs. Escalation path: if resources grow to need validation,
         *     replace `content: Any` with a discriminated union keyed on `name`
         *     and give each resource a typed payload class. The wire envelope
         *     stays the same; the frontend codegen (item 30) then gets per-
         *     resource types for free.
         *
         *     `name` echoes the resource slug the caller requested. Useful when
         *     a response is cached and the cache key needs reconstructing, and
         *     for log messages that correlate a response to its request without
         *     URL parsing.
         */
        ResourceResponse: {
            /** Name */
            name: string;
            /** Content */
            content: unknown;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Scores
             * @description Float scores for each move [0.0 - 1.0]
             */
            scores: number[];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /**
         * SelectStage
         * @description The first and only source stage. Produces the initial pool from
         *     the given selection, ordered by the given key (default: DepthKey).
         */
        SelectStage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "select";
            /** Selection */
            selection: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"] | components["schemas"]["FilterSelection"];
            /** Ordering */
            ordering?: components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"];
        };
        /**
         * ShuffleStage
         * @description Randomize the pool's order in place.
         */
        ShuffleStage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "shuffle";
        };
        /**
         * SiblingSelection
         * @description All cards that share a parent with the context (excluding the context).
         */
        SiblingSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SiblingSelection";
        };
        /**
         * SubtreeSelection
         * @description The subtree rooted at the n-th ancestor (n=0 means rooted at the
         *     context itself), bounded by optional max depth m.
         */
        SubtreeSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SubtreeSelection";
            /**
             * N
             * @default 0
             */
            n: number;
            /** M */
            m?: number | null;
        };
        /** SubtreeSizeKey */
        SubtreeSizeKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SubtreeSizeKey";
        };
        /** TagStat */
        TagStat: {
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /**
         * TakeStage
         * @description Truncate the pool to at most n items.
         */
        TakeStage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "take";
            /** N */
            n: number;
        };
        /** UnionSelection */
        UnionSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "union";
            /** A */
            a: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
            /** B */
            b: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
        };
        /** UserRegister */
        UserRegister: {
            /** Username */
            username: string;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightedSumOrder */
        WeightedSumOrder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WeightedSumOrder";
            /** Terms */
            terms: components["schemas"]["WeightedSumTerm"][];
        };
        /**
         * WeightedSumTerm
         * @description One addend in a WeightedSumOrder. Not a discriminated variant.
         */
        WeightedSumTerm: {
            /** Key */
            key: components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"];
            /** Weight */
            weight: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_user_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_for_access_token_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardWithRecall"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_review_cards__card_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardWithRecall"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_card_cards__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_forest_forests_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForestQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardWithRecall"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_documents__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resources_resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_resource_resources__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tags_stats_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagStat"][];
                };
            };
        };
    };
    get_forests_stats_forests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForestStat"][];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
