/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analysis-bundles/{board_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Bundle
         * @description Fetch the bundle stored under `(user_id, board_id)`, decoded
         *     back to canonical-JSON shape. 404 if no bundle exists OR if
         *     the bundle exists but belongs to a different tenant
         *     (404-not-403 invariant).
         */
        get: operations["get_analysis_bundle_analysis_bundles__board_id__get"];
        /**
         * Upsert Analysis Bundle
         * @description Upsert the analysis bundle stored under
         *     `(user_id, board_id)`. The frontend's "Save analyses" action
         *     is the canonical caller — one PUT replaces the whole bundle
         *     for that board.
         *
         *     The request body's `schema_version` is gated by Pydantic's
         *     `Literal[1]` validator on `AnalysisBundle` (Confirmation C2's
         *     schemaVersion gate; a v2 bundle is a 422 against a v1-only
         *     backend). The two caps — per-bundle (this route's responsibility,
         *     via the service) and per-user (the adapter's, atomic with the
         *     upsert) — both raise to 413 with a structured detail body
         *     discriminated by `kind`.
         */
        put: operations["upsert_analysis_bundle_analysis_bundles__board_id__put"];
        post?: never;
        /**
         * Delete Analysis Bundle
         * @description Idempotent delete. 204 whether or not a row existed.
         *     Cross-tenant deletes are silent no-ops (the WHERE clause's
         *     user_id filter ensures zero-rows-affected for someone else's
         *     board_id).
         */
        delete: operations["delete_analysis_bundle_analysis_bundles__board_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analysis Bundles
         * @description Per-bundle metadata for every bundle the caller owns. No
         *     payloads — the frontend's storage panel uses this to render
         *     "you have N bundles using M GB" without forcing a per-bundle
         *     decode.
         */
        get: operations["list_analysis_bundles_analysis_bundles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Create a new user. If no password is provided, the account is
         *     passwordless and login is governed by config.ALLOW_PASSWORDLESS_LOGIN
         *     at the token endpoint.
         */
        post: operations["register_user_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Project the JWT-bearer's identity to the wire.
         *
         *     Resolves the drift surfaced when a stale token in localStorage
         *     authenticates as one user while the SPA displays another. The SPA
         *     calls this once at bootstrap and trusts what the backend returns
         *     over what its own cache claims.
         *
         *     Three 401 paths converge on the standard credentials-validation
         *     response:
         *       - missing / malformed Bearer (handled by get_current_user_id)
         *       - JWT decodes but `sub` is missing or unparseable (same dep)
         *       - JWT decodes to a user_id whose row no longer exists (here)
         *     All three drop the token client-side; the WWW-Authenticate: Bearer
         *     header signals OAuth2-aware clients to re-auth.
         *
         *     The query projects only (id, username, has_password). The bcrypt
         *     hash is never read into the route layer — a future edit cannot
         *     accidentally widen AuthMeResponse to include it because the column
         *     is not in scope here.
         */
        get: operations["read_current_user_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Review */
        post: operations["submit_review_cards__card_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create New Card */
        post: operations["create_new_card_cards__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forests/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Forest
         * @description Executes a typed pipeline against the given context ids,
         *     restricted to cards owned by the requesting user.
         *
         *     Item 32a: the route no longer constructs the executor inline or
         *     takes a session dependency. The executor is injected fully wired —
         *     both the LineageRepositoryPort and the TagFilterRepositoryPort are
         *     already composed into it by get_pipeline_executor. FastAPI's
         *     dependency caching ensures the session backing both Ports is the
         *     same per-request session.
         *
         *     Item 25 (tenancy): user_id is forwarded to executor.run(), which
         *     threads it through both the lineage Port and the tag-filter Port.
         *     The transitional UserId(1) shim that lived inside PipelineExecutor
         *     until items 13–16 had prepared the Port signatures is gone; the
         *     tenancy spine is fully threaded for /forests/query.
         *
         *     Pydantic has already validated the entire typed DSL (parse-time).
         *     The try/except remains defensive against runtime-only DSL errors —
         *     tag-DSL parse failures inside FilterSelection.tag_expression are
         *     the only remaining runtime PipelineDSLError path (the nested-
         *     filter case from pre-32a is now a parse-time error thanks to the
         *     BaseSelection vs Selection split in domain/pipeline_dsl.py).
         */
        post: operations["query_forest_forests_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Fetch a document by (key, user_id). Returns an empty payload if
         *     no row exists — this preserves the frontend's "missing = empty"
         *     contract (sync-service.ts assumes a fresh install gets {} back,
         *     not 404; item 5 on the frontend documented this).
         *
         *     Item 23 (tenancy): each user gets their own value for any given
         *     key. User A's writes under "user_workspace_settings" are
         *     invisible to user B; user B starts fresh. The empty-payload
         *     convention for missing rows applies per-user, so a brand new
         *     user reading any key gets {}.
         */
        get: operations["get_document_documents__key__get"];
        /**
         * Update Document
         * @description Stateless upsert for document data. Works natively on both
         *     Postgres and SQLite via the SELECT-then-conditional-INSERT
         *     pattern (avoids dialect-specific ON CONFLICT / INSERT OR REPLACE).
         *
         *     Item 23 (tenancy): the existence check filters by (key, user_id).
         *     Without this, user B's first write under a key already used by
         *     user A would fall into the UPDATE branch — and update zero rows
         *     (the WHERE wouldn't match user B's pair), silently failing to
         *     persist. Filtering both the existence check and the UPDATE's
         *     WHERE makes the upsert correct per-tenant.
         *
         *     The composite primary key (key, user_id) on the documents table
         *     enforces the invariant at the database level: a per-user UPSERT
         *     cannot collide with another user's row.
         */
        put: operations["update_document_documents__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/resolve-roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Roots
         * @description For each input card id owned by the caller, identify the game-
         *     source root the card descends from. Group the input by root; list
         *     the unmatched ids (not owned, or not present) explicitly.
         *
         *     Tenancy: the seventh tenant-scoped read path. The Port applies
         *     the user_id filter at both the base case and the recursive step
         *     of its upward-walk CTE. Cross-tenant input ids appear in
         *     `unmatched_card_ids` (the bulk lift of item 13's 404-not-403
         *     posture).
         */
        post: operations["resolve_roots_lineage_resolve_roots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/tree-by-root": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tree By Root
         * @description Return the structure-only subtree rooted at `root_card_id`.
         *
         *     Three response shapes:
         *       - 200: TreeByRootResponse with the recursive `tree` payload.
         *       - 404: root unowned, missing, or not actually a game-source
         *              root. Same 404-not-403 collapse as /cards/{id}.
         *       - 422: tree size exceeds `max_nodes`. Body includes the exact
         *              `actual_size` so the caller can react deliberately.
         *
         *     Tenancy: the eighth tenant-scoped read path. The Port applies
         *     user_id filtering at both the root verification step and at every
         *     level of the descent CTE.
         */
        post: operations["tree_by_root_lineage_tree_by_root_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qeubo/experiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Experiment
         * @description Create-or-replace the user's experiment.
         *
         *     Per dispatch §2.4, if an experiment already exists for this user,
         *     delete it first. The user's `analysis_env.parameters` document
         *     (frontend-side) is unaffected — only Redis state resets.
         */
        post: operations["create_experiment_qeubo_experiment_post"];
        /**
         * Delete Experiment
         * @description Abort and dissolve the user's experiment. 404 if none exists.
         */
        delete: operations["delete_experiment_qeubo_experiment_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qeubo/experiment/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment Status */
        get: operations["get_experiment_status_qeubo_experiment_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qeubo/experiment/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pair
         * @description Fetch (or re-issue) the next A/B pair.
         *
         *     Probes status first to recover `controlled_parameters` and
         *     `parameter_ranges` for decoding; the round-trip cost is one Redis
         *     HMGET, dwarfed by the GP acquisition cost when the runtime fits a
         *     new pair.
         */
        get: operations["get_pair_qeubo_experiment_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qeubo/experiment/preference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Preference
         * @description Record the user's verdict.
         *
         *     Per dispatch §2.4, the bundled-apply semantic ("write the chosen
         *     point's values to `analysis_env.parameters`") is FRONTEND-SIDE.
         *     This route is preference-recording-only.
         */
        post: operations["submit_preference_qeubo_experiment_preference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qeubo/experiment/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Best
         * @description qEUBO's posterior-mean argmax. Heavy compute; may take seconds.
         */
        get: operations["get_best_qeubo_experiment_best_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qeubo/experiment/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Diagnostic: the full ordered preference-triple history.
         */
        get: operations["get_history_qeubo_experiment_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Resources
         * @description List the names of all registered static resources.
         *
         *     Returns a sorted list of slugs that can be fetched via GET
         *     /resources/{name}. Useful for frontend discovery — lets the UI
         *     know what's available without hardcoding the catalog.
         */
        get: operations["list_resources_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resource
         * @description Fetch the content of a named static resource.
         *
         *     Returns a generic envelope: `{"name": <slug>, "content": <any>}`.
         *     The `content` field's shape is resource-specific; consumers are
         *     expected to know what to expect for the resource they asked for.
         *
         *     Raises:
         *         404 (via ResourceNotFoundError): `name` is not registered.
         *             The response body includes a message listing known
         *             resources.
         */
        get: operations["get_resource_resources__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tags
         * @description Returns a list of all tags and their usage counts among the
         *     requesting user's cards.
         *
         *     Item 15 (tenancy): user_id is forwarded to the service, which
         *     forwards to the Port. Tags used only by other tenants appear with
         *     count=0 (the LEFT OUTER JOIN preserves the tag row), making them
         *     indistinguishable from tags with no use at all — the correct
         *     privacy property.
         */
        get: operations["get_tags_stats_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/forests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Forests
         * @description Returns a summary of the requesting user's root game sources,
         *     including the total number of descendant cards, aggregated reviews,
         *     and average Ebisu recall per forest.
         *
         *     Item 15 (tenancy): user_id is forwarded to the service, which
         *     forwards to the Port. The recursive root-mapping CTE filters at
         *     both the base case and the recursive step, ensuring that historical
         *     cross-tenant lineage (if any exists) doesn't leak into a user's
         *     aggregated stats.
         */
        get: operations["get_forests_stats_forests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisBundle
         * @description The bundle stored under one (user_id, board_id) pair.
         *
         *     The upsert wire shape; also the GET response shape (since the
         *     backend reconstructs a canonical-JSON bundle from its stored
         *     `(scheme, payload)` tuple).
         *
         *     `schema_version` gates forward compatibility. The backend
         *     accepts only versions in its known set (today: {1}); a future
         *     v2 bundle adds fields to records without breaking v1 readers,
         *     and the gate prevents a v1-only backend from silently
         *     accepting a v2 bundle it would mis-project.
         */
        AnalysisBundle: {
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Records */
            records: components["schemas"]["AnalysisBundleRecord"][];
        };
        /**
         * AnalysisBundleRecord
         * @description One persisted (config_hash, node_id, packet) tuple.
         *
         *     `packet` is opaque to the backend — a JSON object the frontend
         *     captured from a KataGo analysis response. The backend never
         *     inspects its shape; the codec round-trip preserves it byte-for-
         *     byte (modulo JSON normalisation).
         */
        AnalysisBundleRecord: {
            /** Config Hash */
            config_hash: string;
            /** Node Id */
            node_id: string;
            /** Packet */
            packet: {
                [key: string]: unknown;
            };
        };
        /**
         * AnalysisBundleSummary
         * @description Metadata about a stored bundle — no payload.
         *
         *     The return shape of both `upsert` (the write response) and
         *     `list_summaries` (the per-board listing). The dispatch named
         *     the upsert-return as AnalysisBundleStored and the list-element
         *     as AnalysisBundleSummary, but the two shapes are identical and
         *     the semantic is the same ("metadata about a stored bundle"),
         *     so they collapse to one DTO here.
         *
         *     `stored_byte_size` is the post-transcoding byte count — the
         *     same value the per-user quota check sums (Confirmation C3 in
         *     the dispatch). The frontend's storage panel sums this across
         *     a list response to display "X of 2 GB used"; backend's quota
         *     check on the next PUT operates on the same value.
         */
        AnalysisBundleSummary: {
            /**
             * Board Id
             * Format: uuid
             */
            board_id: string;
            /** Record Count */
            record_count: number;
            /** Stored Scheme */
            stored_scheme: string;
            /** Stored Byte Size */
            stored_byte_size: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AncestorSelection
         * @description The n-th ancestor of the context card (n=1 means parent).
         */
        AncestorSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "AncestorSelection";
            /**
             * N
             * @default 1
             */
            n: number;
        };
        /**
         * AuthMeResponse
         * @description Identity-projection wire shape for GET /auth/me.
         *
         *     Mirrors the three non-credential columns of the `users` table.
         *     `bcrypt_hash` is intentionally absent — it never crosses the wire.
         */
        AuthMeResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Has Password */
            has_password: boolean;
        };
        /** BestResponse */
        BestResponse: {
            /** Point */
            point: number[];
            /** Values */
            values: {
                [key: string]: number;
            };
            /** Phase */
            phase: string;
            /** Iteration */
            iteration: number;
        };
        /**
         * BfsOrder
         * @description Equivalent to DepthKey.
         */
        BfsOrder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bfs_order";
        };
        /** Body_login_for_access_token_auth_token_post */
        Body_login_for_access_token_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * CardCreate
         * @description Request body shape for POST /cards/.
         *
         *     Post-34b Commit 3: only `raw_content` is accepted for the content
         *     field. The transitional alias for `sgf` is gone. If the frontend
         *     sends a legacy shape the request fails at parse time with a
         *     clear Pydantic error — which is the correct diagnostic, not a
         *     silent misbinding.
         *
         *     Domain-specific grading configuration (KataGo visits, palette,
         *     gamma) travels inside `grading_parameter.data`. This DTO doesn't
         *     validate the blob's contents — it's the frontend's contract with
         *     the specific backend grading logic.
         */
        CardCreate: {
            /** Num Moves */
            num_moves: number;
            /** Grading Parameter */
            grading_parameter?: {
                [key: string]: unknown;
            } | null;
            /**
             * Raw Content
             * @description The raw domain content (SGF for Go, PGN for Chess, etc.). Normalized canonically by the configured PositionNormalizer before storage.
             */
            raw_content: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Parent Card Id */
            parent_card_id?: number | null;
            game_metadata?: components["schemas"]["GameSourceCreate"] | null;
        };
        /**
         * CardCreateResponse
         * @description Strongly-typed response for POST /cards/. Replaces the prior
         *     Dict[str, Any], which provided no information to OpenAPI consumers
         *     (and therefore no information to any code-generated TypeScript
         *     client downstream — see item 30). Item 4.
         */
        CardCreateResponse: {
            /**
             * Status
             * @constant
             */
            status: "created";
            /** Card Id */
            card_id: number;
        };
        /**
         * CardWithRecall
         * @description A Card augmented with its current Bayesian recall projection.
         *
         *     The wire shape returned by GET /cards/{id},
         *     POST /cards/{id}/review, and POST /forests/query.
         *
         *     Post-34b-Commit-3b: emits only canonical field names. The
         *     stale-client compat shims that synthesized `normalized_sgf` and
         *     top-level `default_visits` for browsers running pre-Commit-2
         *     bundles have been removed — the stale-bundle window has closed
         *     and frontend code reads exclusively from the canonical fields.
         *
         *     Any client that still reads `response.normalized_sgf` or
         *     `response.default_visits` will get `undefined` from this point
         *     on. The frontend's `34b-cleanup` removes the corresponding
         *     fallback chains in `mapToReviewCard` in tandem with this commit.
         */
        CardWithRecall: {
            /** Id */
            id: number;
            /** Num Moves */
            num_moves: number;
            /** Alpha */
            alpha: number;
            /** Beta */
            beta: number;
            /** T */
            t: number;
            /** Last Reviewed At */
            last_reviewed_at: string | null;
            /**
             * Creation Date
             * Format: date-time
             */
            creation_date: string;
            /** Num Reviews */
            num_reviews: number;
            /** Suspended */
            suspended: boolean;
            /** Grading Parameter */
            grading_parameter: {
                [key: string]: unknown;
            } | null;
            /** Canonical Content */
            canonical_content: string;
            /** Card Source Id */
            card_source_id?: number | null;
            /** Current Recall */
            current_recall: number;
            /** Halflife Units */
            halflife_units: number;
        };
        /**
         * CentroidOrder
         * @description Equivalent to CentroidRankKey.
         */
        CentroidOrder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "centroid_order";
        };
        /** CentroidRankKey */
        CentroidRankKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CentroidRankKey";
        };
        /**
         * ConfigOverrides
         * @description Optional overrides forwarded into the runtime's `user_config`.
         *
         *     `extra="allow"` keeps the wire shape forward-compatible with any
         *     upstream config keys the runtime may grow without forcing a wire-
         *     schema bump every time.
         */
        ConfigOverrides: {
            /** Num Init Queries */
            num_init_queries?: number | null;
            /** Num Algo Queries */
            num_algo_queries?: number | null;
            /** Noise Type */
            noise_type?: string | null;
            /** Noise Level */
            noise_level?: number | null;
            /** Num Alternatives */
            num_alternatives?: number | null;
            /** Model Type */
            model_type?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ContextSelection
         * @description Just the context card itself.
         */
        ContextSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ContextSelection";
        };
        /** CreateExperimentRequest */
        CreateExperimentRequest: {
            /** Controlled Parameters */
            controlled_parameters: string[];
            /** Parameter Ranges */
            parameter_ranges: {
                [key: string]: number[];
            };
            config_overrides?: components["schemas"]["ConfigOverrides"] | null;
        };
        /** CreateExperimentResponse */
        CreateExperimentResponse: {
            /** Experiment Id */
            experiment_id: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Controlled Parameters */
            controlled_parameters: string[];
            /** Phase */
            phase: string;
            /** Init Index */
            init_index: number;
            /** Num Init Queries */
            num_init_queries: number;
            /** Iteration */
            iteration: number;
            /** Num Algo Queries */
            num_algo_queries: number;
        };
        /** DepthKey */
        DepthKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DepthKey";
        };
        /**
         * DescendantSelection
         * @description All cards descended from the context, optionally bounded by depth.
         */
        DescendantSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DescendantSelection";
            /** Max Depth */
            max_depth?: number | null;
        };
        /**
         * DfsPostorder
         * @description Equivalent to LexicographicOrder(keys=[HeightKey, HeavyPathRankKey]).
         */
        DfsPostorder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dfs_postorder";
        };
        /**
         * DfsPreorder
         * @description Equivalent to HeavyPathRankKey.
         */
        DfsPreorder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dfs_preorder";
        };
        /** DocumentUpdate */
        DocumentUpdate: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** EbisuRecallKey */
        EbisuRecallKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "EbisuRecallKey";
        };
        /**
         * FilterSelection
         * @description Wraps a BaseSelection with a tag-DSL expression. By design,
         *     `base` is typed as BaseSelection — filter cannot be nested inside
         *     another filter. This is a parse-time invariant; the previous
         *     runtime check in build_selection_cte (item 31) is no longer
         *     reachable for well-typed input.
         */
        FilterSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "filter";
            /** Tag Expression */
            tag_expression: string;
            /** Base */
            base: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
        };
        /**
         * ForestQuery
         * @description The wire-level request body for POST /forests/query.
         *
         *     Structural invariants enforced by a model_validator:
         *       1. First stage must be 'select'.
         *       2. No subsequent stage may be 'select'.
         *
         *     Field-level validation (each variant's fields, each numeric bound,
         *     each discriminator value) is handled by Pydantic's discriminated-
         *     union machinery. The recently-added nested-filter rule (32a) is
         *     enforced by BaseSelection's absence of FilterSelection — no runtime
         *     check needed.
         */
        ForestQuery: {
            /** Context Ids */
            context_ids: number[];
            /** Pipeline */
            pipeline: (components["schemas"]["SelectStage"] | components["schemas"]["TakeStage"] | components["schemas"]["ShuffleStage"] | components["schemas"]["OrderStage"])[];
        };
        /** ForestStat */
        ForestStat: {
            /** Root Card Id */
            root_card_id: number;
            /** Game Source Id */
            game_source_id: number;
            /** Description */
            description: string | null;
            /** Player White */
            player_white: string | null;
            /** Player Black */
            player_black: string | null;
            /** Total Cards */
            total_cards: number;
            /** Total Reviews */
            total_reviews: number;
            /** Average Recall */
            average_recall: number;
        };
        /**
         * FringeFirst
         * @description Equivalent to LexicographicOrder(keys=[HeightKey, DepthKey]).
         */
        FringeFirst: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fringe_first";
        };
        /**
         * GameSourceCreate
         * @description Metadata for minting a brand new root card.
         *
         *     Game-source dedup: `client_game_id` is an opaque
         *     client-managed UUID. When set, the backend uses it as a
         *     get-or-create key on `(user_id, client_game_id)` so multiple
         *     mints from one board's lifetime resolve to a single game_source
         *     row (and a single forest-navigator entry). When unset, the
         *     backend falls through to the historical always-create behavior,
         *     preserving any caller that doesn't speak the new wire (curl,
         *     test fixtures, pre-rollout frontends).
         *
         *     First-mint-wins semantic: when the client_game_id matches an
         *     existing row, the existing row's player_white / player_black /
         *     description are preserved; the incoming values on the second
         *     mint are ignored. This matches user intent — editing SGF root
         *     properties between mints from one board shouldn't retroactively
         *     rewrite the game's recorded metadata.
         *
         *     See `docs/dispatch/backend-to-frontend-game-source-dedup-status.md`
         *     for the wire-shape rationale.
         */
        GameSourceCreate: {
            /** Player White */
            player_white?: string | null;
            /** Player Black */
            player_black?: string | null;
            /** Description */
            description?: string | null;
            /** Client Game Id */
            client_game_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeavyPathRankKey */
        HeavyPathRankKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HeavyPathRankKey";
        };
        /** HeightKey */
        HeightKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HeightKey";
        };
        /**
         * HistoryResponse
         * @description The runtime's history-triple shape is undocumented in
         *     `backend/qeubo/README.md`; pass it through verbatim under
         *     `history` typed as `list[Any]` rather than guessing.
         */
        HistoryResponse: {
            /** History */
            history: unknown[];
            /** Phase */
            phase: string;
            /** Iteration */
            iteration: number;
            /** Total Responses */
            total_responses: number;
        };
        /** IntersectSelection */
        IntersectSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "intersect";
            /** A */
            a: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
            /** B */
            b: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
        };
        /** LexicographicOrder */
        LexicographicOrder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LexicographicOrder";
            /** Keys */
            keys: (components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"])[];
        };
        /**
         * MainLineFirst
         * @description Equivalent to LexicographicOrder(keys=[HeavyPathRankKey, NumReviewsKey]).
         */
        MainLineFirst: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "main_line_first";
        };
        /** Negated */
        Negated: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "negated";
            /** Key */
            key: components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"];
        };
        /** NumMovesKey */
        NumMovesKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NumMovesKey";
        };
        /** NumReviewsKey */
        NumReviewsKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NumReviewsKey";
        };
        /**
         * OrderStage
         * @description Re-sort the pool by the given key.
         */
        OrderStage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "order";
            /** Ordering */
            ordering: components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"];
        };
        /** PairResponse */
        PairResponse: {
            /** Query Uuid */
            query_uuid: string;
            /** Point A */
            point_a: number[];
            /** Point B */
            point_b: number[];
            /** Values A */
            values_a: {
                [key: string]: number;
            };
            /** Values B */
            values_b: {
                [key: string]: number;
            };
            /** Phase */
            phase: string;
            /** Iteration */
            iteration: number;
            /** Reissued */
            reissued: boolean;
        };
        /** PreferenceRequest */
        PreferenceRequest: {
            /** Query Uuid */
            query_uuid: string;
            /** Preferred */
            preferred: number;
        };
        /** PreferenceResponse */
        PreferenceResponse: {
            /** Phase */
            phase: string;
            /** Iteration */
            iteration: number;
            /** Init Index */
            init_index: number;
            /** Total Responses */
            total_responses: number;
            /** Completed */
            completed: boolean;
        };
        /**
         * ResolveRootsRequest
         * @description Bulk input to /lineage/resolve-roots: a list of card ids the
         *     caller wants grouped by their game-source root.
         *
         *     Empty list is a valid input (resolve-roots returns an empty
         *     response). The route does not impose an upper bound on list size;
         *     the underlying CTE is one round trip regardless of input length.
         */
        ResolveRootsRequest: {
            /** Card Ids */
            card_ids: number[];
        };
        /**
         * ResolveRootsResponse
         * @description Response shape for /lineage/resolve-roots.
         *
         *     `roots` and `unmatched_card_ids` partition the original input —
         *     every input id appears in exactly one of the two — so the caller
         *     knows whether a missing id was unowned or never existed (the
         *     bulk lift of the per-card 404-not-403 invariant).
         */
        ResolveRootsResponse: {
            /** Roots */
            roots: components["schemas"]["ResolvedRoot"][];
            /** Unmatched Card Ids */
            unmatched_card_ids: number[];
        };
        /**
         * ResolvedRoot
         * @description One game-source root and the input cards that descend from it.
         */
        ResolvedRoot: {
            /** Root Card Id */
            root_card_id: number;
            /** Game Source Id */
            game_source_id: number;
            /** Card Ids In Tree */
            card_ids_in_tree: number[];
        };
        /**
         * ResourceResponse
         * @description The wire shape for GET /resources/{name}.
         *
         *     Generic envelope: `content` is typed as `Any` because the payload
         *     shape varies per resource. This is a deliberate concession —
         *     Pydantic doesn't validate the inner structure, and downstream
         *     consumers (the frontend) are responsible for knowing the shape
         *     for the resource they asked for.
         *
         *     The alternative (discriminated union typed per resource) would be
         *     architecturally purer but over-engineered for a handful of static
         *     JSON blobs. Escalation path: if resources grow to need validation,
         *     replace `content: Any` with a discriminated union keyed on `name`
         *     and give each resource a typed payload class. The wire envelope
         *     stays the same; the frontend codegen (item 30) then gets per-
         *     resource types for free.
         *
         *     `name` echoes the resource slug the caller requested. Useful when
         *     a response is cached and the cache key needs reconstructing, and
         *     for log messages that correlate a response to its request without
         *     URL parsing.
         */
        ResourceResponse: {
            /** Name */
            name: string;
            /** Content */
            content: unknown;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Scores
             * @description Float scores for each move [0.0 - 1.0]
             */
            scores: number[];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /**
         * SelectStage
         * @description The first and only source stage. Produces the initial pool from
         *     the given selection, ordered by the given key (default: DepthKey).
         */
        SelectStage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "select";
            /** Selection */
            selection: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"] | components["schemas"]["FilterSelection"];
            /** Ordering */
            ordering?: components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"];
        };
        /**
         * ShuffleStage
         * @description Randomize the pool's order in place.
         */
        ShuffleStage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "shuffle";
        };
        /**
         * SiblingSelection
         * @description All cards that share a parent with the context (excluding the context).
         */
        SiblingSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SiblingSelection";
        };
        /** StatusResponse */
        StatusResponse: {
            /** Experiment Id */
            experiment_id: string;
            /** Phase */
            phase: string;
            /** Init Index */
            init_index: number;
            /** Num Init Queries */
            num_init_queries: number;
            /** Iteration */
            iteration: number;
            /** Num Algo Queries */
            num_algo_queries: number;
            /** Total Responses */
            total_responses: number;
            /** Has Pending */
            has_pending: boolean;
            /** Pending Query Uuid */
            pending_query_uuid: string | null;
        };
        /**
         * SubtreeSelection
         * @description The subtree rooted at the n-th ancestor (n=0 means rooted at the
         *     context itself), bounded by optional max depth m.
         */
        SubtreeSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SubtreeSelection";
            /**
             * N
             * @default 0
             */
            n: number;
            /** M */
            m?: number | null;
        };
        /** SubtreeSizeKey */
        SubtreeSizeKey: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SubtreeSizeKey";
        };
        /** TagStat */
        TagStat: {
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /**
         * TakeStage
         * @description Truncate the pool to at most n items.
         */
        TakeStage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            stage: "take";
            /** N */
            n: number;
        };
        /**
         * TreeByRootRequest
         * @description Input to /lineage/tree-by-root.
         *
         *     `max_nodes` defaults to 10000 per the spec. The route accepts an
         *     explicit override if the caller knows it wants a smaller cap (e.g.
         *     a UI that previews only the top of a tree); the lower bound is
         *     1, enforced at the Pydantic layer rather than discovered as a
         *     runtime overflow.
         */
        TreeByRootRequest: {
            /** Root Card Id */
            root_card_id: number;
            /**
             * Max Nodes
             * @default 10000
             */
            max_nodes: number | null;
        };
        /**
         * TreeByRootResponse
         * @description Response shape for /lineage/tree-by-root.
         *
         *     On overflow the route returns 422 with a structured detail body
         *     (see `_overflow_detail` below) instead of this shape.
         */
        TreeByRootResponse: {
            /** Root Card Id */
            root_card_id: number;
            /** Game Source Id */
            game_source_id: number;
            tree: components["schemas"]["TreeNode"];
        };
        /**
         * TreeNode
         * @description A recursive structure-only tree node: id and children only.
         */
        TreeNode: {
            /** Id */
            id: number;
            /** Children */
            children: components["schemas"]["TreeNode"][];
        };
        /** UnionSelection */
        UnionSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "union";
            /** A */
            a: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
            /** B */
            b: components["schemas"]["ContextSelection"] | components["schemas"]["DescendantSelection"] | components["schemas"]["AncestorSelection"] | components["schemas"]["SiblingSelection"] | components["schemas"]["SubtreeSelection"] | components["schemas"]["UnionSelection"] | components["schemas"]["IntersectSelection"];
        };
        /** UserRegister */
        UserRegister: {
            /** Username */
            username: string;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeightedSumOrder */
        WeightedSumOrder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WeightedSumOrder";
            /** Terms */
            terms: components["schemas"]["WeightedSumTerm"][];
        };
        /**
         * WeightedSumTerm
         * @description One addend in a WeightedSumOrder. Not a discriminated variant.
         */
        WeightedSumTerm: {
            /** Key */
            key: components["schemas"]["DepthKey"] | components["schemas"]["HeightKey"] | components["schemas"]["SubtreeSizeKey"] | components["schemas"]["HeavyPathRankKey"] | components["schemas"]["CentroidRankKey"] | components["schemas"]["NumReviewsKey"] | components["schemas"]["NumMovesKey"] | components["schemas"]["EbisuRecallKey"] | components["schemas"]["Negated"] | components["schemas"]["LexicographicOrder"] | components["schemas"]["WeightedSumOrder"] | components["schemas"]["BfsOrder"] | components["schemas"]["DfsPreorder"] | components["schemas"]["DfsPostorder"] | components["schemas"]["FringeFirst"] | components["schemas"]["CentroidOrder"] | components["schemas"]["MainLineFirst"];
            /** Weight */
            weight: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_analysis_bundle_analysis_bundles__board_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_analysis_bundle_analysis_bundles__board_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisBundle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisBundleSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_bundle_analysis_bundles__board_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analysis_bundles_analysis_bundles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisBundleSummary"][];
                };
            };
        };
    };
    register_user_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_for_access_token_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
        };
    };
    get_card_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardWithRecall"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_review_cards__card_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardWithRecall"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_card_cards__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_forest_forests_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForestQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardWithRecall"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_documents__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_roots_lineage_resolve_roots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRootsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveRootsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tree_by_root_lineage_tree_by_root_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TreeByRootRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeByRootResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_qeubo_experiment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateExperimentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_experiment_qeubo_experiment_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_experiment_status_qeubo_experiment_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_pair_qeubo_experiment_pair_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairResponse"];
                };
            };
        };
    };
    submit_preference_qeubo_experiment_preference_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_best_qeubo_experiment_best_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestResponse"];
                };
            };
        };
    };
    get_history_qeubo_experiment_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
        };
    };
    list_resources_resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_resource_resources__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tags_stats_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagStat"][];
                };
            };
        };
    };
    get_forests_stats_forests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForestStat"][];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
